// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RESTful_Api_Exp2.Data;

namespace RESTful_Api_Exp2.Migrations
{
    [DbContext(typeof(Restful_DbContext))]
    [Migration("20210528051524_initialMigration3")]
    partial class initialMigration3
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.5");

            modelBuilder.Entity("RESTful_Api_Exp2.Entities.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Industry")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Introduction")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Product")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a3a461ea-e692-6f54-2f3e-f076a08dda14"),
                            Country = "USA",
                            Industry = "Software",
                            Introduction = "Good Company",
                            Name = "WeiRuan",
                            Product = "VisualStudio"
                        },
                        new
                        {
                            Id = new Guid("6c561b72-f44b-40ee-ba4b-a77d17aa8fff"),
                            Country = "China",
                            Industry = "e-commerce",
                            Introduction = "Bad Company",
                            Name = "PDD",
                            Product = "Kan yi dao"
                        },
                        new
                        {
                            Id = new Guid("a06b7e5d-83e7-473d-ad40-79d9fadfadb8"),
                            Country = "China",
                            Industry = "e-commerce",
                            Introduction = "Fuck 996",
                            Name = "Alibaba",
                            Product = "996 ICU"
                        },
                        new
                        {
                            Id = new Guid("bf6ca130-51af-4e42-aee6-16a2b922c8b8"),
                            Country = "China",
                            Industry = "e-commerce",
                            Introduction = "996 icu 007 death",
                            Name = "DreamCompany1",
                            Product = "996 ICU"
                        },
                        new
                        {
                            Id = new Guid("136fa82f-57f7-4479-90cc-8dc4198d0ec1"),
                            Country = "China",
                            Industry = "e-commerce",
                            Introduction = "996 icu 007 death",
                            Name = "DreamCompany2",
                            Product = "996 ICU"
                        },
                        new
                        {
                            Id = new Guid("b80d95ba-30fc-4eb9-b138-7b841497b457"),
                            Country = "China",
                            Industry = "e-commerce",
                            Introduction = "996 icu 007 death",
                            Name = "DreamCompany3",
                            Product = "996 ICU"
                        },
                        new
                        {
                            Id = new Guid("5f05d00d-11c5-4796-9f86-270ccd9560e0"),
                            Country = "China",
                            Industry = "e-commerce",
                            Introduction = "996 icu 007 death",
                            Name = "DreamCompany4",
                            Product = "996 ICU"
                        },
                        new
                        {
                            Id = new Guid("d103dd72-ef31-45d5-a9ff-0b2bd17788a8"),
                            Country = "China",
                            Industry = "e-commerce",
                            Introduction = "996 icu 007 death",
                            Name = "DreamCompany5",
                            Product = "996 ICU"
                        });
                });

            modelBuilder.Entity("RESTful_Api_Exp2.Entities.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmployeeNo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("Gender")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("HiredDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("PhotoFileName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a3a461ea-e692-6f54-2f3e-f076a08dda15"),
                            CompanyId = new Guid("a3a461ea-e692-6f54-2f3e-f076a08dda14"),
                            EmployeeNo = "00001",
                            FirstName = "Xiaopeng",
                            Gender = 1,
                            HiredDate = new DateTime(2021, 4, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Luo",
                            PhotoFileName = ""
                        },
                        new
                        {
                            Id = new Guid("6c561b72-f44b-40ee-ba4b-a77d17aa8fef"),
                            CompanyId = new Guid("a3a461ea-e692-6f54-2f3e-f076a08dda14"),
                            EmployeeNo = "00002",
                            FirstName = "Guanxi",
                            Gender = 1,
                            HiredDate = new DateTime(2015, 3, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Chen",
                            PhotoFileName = ""
                        },
                        new
                        {
                            Id = new Guid("a06b7e5d-83e7-473d-ad40-79d9fadfadc8"),
                            CompanyId = new Guid("a06b7e5d-83e7-473d-ad40-79d9fadfadb8"),
                            EmployeeNo = "00003",
                            FirstName = "Donald",
                            Gender = 1,
                            HiredDate = new DateTime(2021, 4, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Trump",
                            PhotoFileName = ""
                        });
                });

            modelBuilder.Entity("RESTful_Api_Exp2.Entities.EmployeeTask", b =>
                {
                    b.Property<Guid>("taskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Deadline")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("EmployeeId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("TaskDescription")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("TaskName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("taskId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("EmployeeTasks");

                    b.HasData(
                        new
                        {
                            taskId = new Guid("c2e5433f-0b26-45ca-9d71-7c5e54af6617"),
                            Deadline = new DateTime(2021, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = new Guid("a3a461ea-e692-6f54-2f3e-f076a08dda15"),
                            StartTime = new DateTime(2021, 5, 28, 0, 15, 23, 869, DateTimeKind.Local).AddTicks(2826),
                            TaskDescription = "fixxxxxxxxxxxxxxxxxxxxxxx buggggggggggggggggs",
                            TaskName = "fix bugs"
                        },
                        new
                        {
                            taskId = new Guid("05647a01-d14f-4893-b85b-e277e209ae52"),
                            Deadline = new DateTime(2021, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = new Guid("a3a461ea-e692-6f54-2f3e-f076a08dda15"),
                            StartTime = new DateTime(2021, 4, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TaskDescription = "test ttttttttttttttt",
                            TaskName = "test"
                        },
                        new
                        {
                            taskId = new Guid("5ce682ef-bc20-4e11-bce6-12916576698e"),
                            Deadline = new DateTime(2021, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = new Guid("a06b7e5d-83e7-473d-ad40-79d9fadfadc8"),
                            StartTime = new DateTime(2021, 5, 28, 0, 0, 0, 0, DateTimeKind.Local),
                            TaskDescription = "make america great again",
                            TaskName = "bullshit"
                        },
                        new
                        {
                            taskId = new Guid("26cd2cef-928e-40a4-99e1-7fe7770be4ac"),
                            Deadline = new DateTime(2021, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = new Guid("a3a461ea-e692-6f54-2f3e-f076a08dda15"),
                            StartTime = new DateTime(2021, 4, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TaskDescription = "create a new table, query all task list, delete a row",
                            TaskName = "play"
                        },
                        new
                        {
                            taskId = new Guid("52b2279e-38a4-4d85-9d6c-3fa196ea3b24"),
                            Deadline = new DateTime(2021, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = new Guid("a3a461ea-e692-6f54-2f3e-f076a08dda15"),
                            StartTime = new DateTime(2021, 4, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TaskDescription = "I know your monster, I know your pain",
                            TaskName = "go home"
                        },
                        new
                        {
                            taskId = new Guid("9e0dd20e-659d-4f37-87be-9b24b7b69b98"),
                            Deadline = new DateTime(2021, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = new Guid("a3a461ea-e692-6f54-2f3e-f076a08dda15"),
                            StartTime = new DateTime(2021, 4, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TaskDescription = "I know your monster, I know your pain",
                            TaskName = "go home again"
                        },
                        new
                        {
                            taskId = new Guid("747e7a32-3876-44ce-b85f-dd557b2984d9"),
                            Deadline = new DateTime(2021, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = new Guid("6c561b72-f44b-40ee-ba4b-a77d17aa8fef"),
                            StartTime = new DateTime(2021, 4, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TaskDescription = "I know your monster, I know your pain",
                            TaskName = "go home2"
                        },
                        new
                        {
                            taskId = new Guid("98549e15-5596-4d43-9106-0bd2d67bf7c8"),
                            Deadline = new DateTime(2021, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = new Guid("a06b7e5d-83e7-473d-ad40-79d9fadfadc8"),
                            StartTime = new DateTime(2021, 4, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TaskDescription = "I know your monster, I know your pain",
                            TaskName = "go home3"
                        },
                        new
                        {
                            taskId = new Guid("84bdba17-e4d6-4b2a-8ade-7d8606eff3ea"),
                            Deadline = new DateTime(2021, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = new Guid("a3a461ea-e692-6f54-2f3e-f076a08dda15"),
                            StartTime = new DateTime(2021, 4, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TaskDescription = "I know your monster, I know your pain",
                            TaskName = "go home4"
                        },
                        new
                        {
                            taskId = new Guid("d547664e-249d-4f88-b1db-dcfd0bf3d623"),
                            Deadline = new DateTime(2021, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = new Guid("6c561b72-f44b-40ee-ba4b-a77d17aa8fef"),
                            StartTime = new DateTime(2021, 4, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TaskDescription = "I know your monster, I know your pain",
                            TaskName = "go home5"
                        });
                });

            modelBuilder.Entity("RESTful_Api_Exp2.Entities.Employee", b =>
                {
                    b.HasOne("RESTful_Api_Exp2.Entities.Company", "Company")
                        .WithMany("Employees")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("RESTful_Api_Exp2.Entities.EmployeeTask", b =>
                {
                    b.HasOne("RESTful_Api_Exp2.Entities.Employee", "Employees")
                        .WithMany("Tasklist")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Employees");
                });

            modelBuilder.Entity("RESTful_Api_Exp2.Entities.Company", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("RESTful_Api_Exp2.Entities.Employee", b =>
                {
                    b.Navigation("Tasklist");
                });
#pragma warning restore 612, 618
        }
    }
}
