// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RESTful_Api_Exp2.Data;

namespace RESTful_Api_Exp2.Migrations
{
    [DbContext(typeof(Restful_DbContext))]
    [Migration("20210422211450_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.5");

            modelBuilder.Entity("RESTful_Api_Exp2.Entities.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Introduction")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a3a461ea-e692-6f54-2f3e-f076a08dda14"),
                            Introduction = "Good Company",
                            Name = "WeiRuan"
                        },
                        new
                        {
                            Id = new Guid("6c561b72-f44b-40ee-ba4b-a77d17aa8fff"),
                            Introduction = "Bad Company",
                            Name = "PDD"
                        },
                        new
                        {
                            Id = new Guid("a06b7e5d-83e7-473d-ad40-79d9fadfadb8"),
                            Introduction = "Fuck 996",
                            Name = "Alibaba"
                        });
                });

            modelBuilder.Entity("RESTful_Api_Exp2.Entities.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmployeeNo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("Gender")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("HiredDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("RESTful_Api_Exp2.Entities.EmployeeTask", b =>
                {
                    b.Property<Guid>("taskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Dateline")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("TaskDescription")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("TaskName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("taskId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("EmployeeTasks");
                });

            modelBuilder.Entity("RESTful_Api_Exp2.Entities.Employee", b =>
                {
                    b.HasOne("RESTful_Api_Exp2.Entities.Company", "Company")
                        .WithMany("Employees")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("RESTful_Api_Exp2.Entities.EmployeeTask", b =>
                {
                    b.HasOne("RESTful_Api_Exp2.Entities.Employee", "Employees")
                        .WithMany("Tasklist")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employees");
                });

            modelBuilder.Entity("RESTful_Api_Exp2.Entities.Company", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("RESTful_Api_Exp2.Entities.Employee", b =>
                {
                    b.Navigation("Tasklist");
                });
#pragma warning restore 612, 618
        }
    }
}
